# fly.toml file generated for blindy-youtube-downloader on 2023-04-02T21:05:22-04:00

app = "blindy-youtube-downloader"
#kill_signal = "SIGINT"
#kill_timeout = 5
primary_region = "ewr"
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 100
    soft_limit = 100

  [[services.ports]]
    handlers = ["http"]
    port = "80"
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000